import { useMemo, useState } from "react";
import {
  Archive, BarChart3, Bell, BookOpen, CalendarDays, Check, ChevronLeft, ChevronRight,
  Clipboard, Clock3, Copy, Edit3, FileText, GraduationCap, Hash, KeyRound, Layers3,
  Megaphone, MessageCircle, MoreHorizontal, Pin, Plus, RefreshCw, Search, Send,
  ShieldCheck, Trash2, TrendingUp, UserCheck, UserMinus, Users, X
} from "lucide-react";
import { BATCH_STUDENTS, blankBatch, blankSubject } from "../batches/batch.data.js";

function date(value) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", hour: value?.includes("T") ? "numeric" : undefined, minute: value?.includes("T") ? "2-digit" : undefined }).format(new Date(value)); }

function WorkspaceModal({ title, subtitle, onClose, children, wide = false }) {
  return <div className="workspace-modal-backdrop" onMouseDown={(event) => event.target === event.currentTarget && onClose()}><section className={`workspace-modal ${wide ? "wide" : ""}`} role="dialog" aria-modal="true"><header><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div><button onClick={onClose} aria-label="Close"><X /></button></header>{children}</section></div>;
}

function BatchEditor({ initial, user, onSave, onClose, showToast }) {
  const [form, setForm] = useState(() => ({ ...blankBatch(user?.name), ...initial }));
  const [error, setError] = useState("");
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  function submit(event) { event.preventDefault(); if (!form.name.trim() || !form.subject.trim() || !form.description.trim()) { setError("Batch name, subject, and description are required."); return; } onSave({ ...form, capacity: Number(form.capacity) }); showToast?.(form.id ? "Batch updated" : "Batch created with a unique join code"); onClose(); }
  return <WorkspaceModal title={form.id ? "Edit batch" : "Create batch"} subtitle="Organize students, subjects, and learning activity." onClose={onClose} wide><form className="workspace-form" onSubmit={submit}><div className="workspace-form-grid"><label className="span-2"><span>Batch name *</span><input value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="Backend Engineering - Cohort 8" /></label><label><span>Primary subject *</span><input value={form.subject} onChange={(e) => update("subject", e.target.value)} placeholder="Backend Engineering" /></label><label><span>Department</span><input value={form.department} onChange={(e) => update("department", e.target.value)} /></label><label><span>Semester</span><select value={form.semester} onChange={(e) => update("semester", e.target.value)}><option>Semester 1</option><option>Semester 2</option><option>Semester 3</option><option>Semester 4</option></select></label><label><span>Year</span><input value={form.year} onChange={(e) => update("year", e.target.value)} /></label><label><span>Capacity</span><input type="number" min="1" max="500" value={form.capacity} onChange={(e) => update("capacity", e.target.value)} /></label><label><span>Teacher</span><input value={form.teacher} onChange={(e) => update("teacher", e.target.value)} /></label><label><span>Status</span><select value={form.status} onChange={(e) => update("status", e.target.value)}><option>Active</option><option>Archived</option></select></label><label className="span-2"><span>Description *</span><textarea rows="4" value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="What will this batch learn?" /></label></div>{error && <p className="workspace-error">{error}</p>}<footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Check /> Save batch</button></footer></form></WorkspaceModal>;
}

function BatchCards({ batches, state, onOpen, onEdit, onArchive, onDelete }) {
  return <div className="batch-card-grid">{batches.map((batch) => <article className={batch.status === "Archived" ? "archived" : ""} key={batch.id}><header><span><Layers3 /></span><div><small>{batch.department}</small><h2>{batch.name}</h2></div><span className={`batch-status ${batch.status.toLowerCase()}`}>{batch.status}</span></header><p>{batch.description}</p><div className="batch-card-meta"><span><GraduationCap />{batch.semester}, {batch.year}</span><span><BookOpen />{batch.subjectIds.length} subjects</span><span><Users />{batch.studentIds.length}/{batch.capacity} students</span></div><div className="batch-completion"><span><strong>{batch.completion}%</strong> completion</span><div><i style={{ width: `${batch.completion}%` }} /></div></div><footer><button className="batch-open" onClick={() => onOpen(batch.id)}>View batch <ChevronRight /></button><div><button title="Edit batch" onClick={() => onEdit(batch)}><Edit3 /></button><button title={batch.status === "Archived" ? "Restore batch" : "Archive batch"} onClick={() => onArchive(batch.id)}><Archive /></button><button title="Delete batch" className="danger" onClick={() => onDelete(batch)}><Trash2 /></button></div></footer></article>)}</div>;
}

function JoinCodeCard({ batch, store, showToast }) {
  async function copy() { await navigator.clipboard?.writeText(batch.joinCode); showToast?.("Join code copied"); }
  return <section className={`join-code-card ${batch.joinCodeEnabled ? "" : "disabled"}`}><header><div><KeyRound /><span><strong>Student join code</strong><small>{batch.joinCodeEnabled ? "Students can join this batch" : "Joining is currently disabled"}</small></span></div><span>{batch.joinCodeEnabled ? "Enabled" : "Disabled"}</span></header><div><code>{batch.joinCode}</code><button onClick={copy}><Copy /> Copy</button></div><footer><button onClick={() => { store.regenerateJoinCode(batch.id); showToast?.("New join code generated"); }}><RefreshCw /> Regenerate</button><button onClick={() => { store.toggleJoinCode(batch.id); showToast?.(batch.joinCodeEnabled ? "Join code disabled" : "Join code enabled"); }}><ShieldCheck /> {batch.joinCodeEnabled ? "Disable" : "Enable"}</button></footer></section>;
}

function OverviewTab({ batch, state, assessmentStore, store, showToast }) {
  const subjects = state.subjects.filter((item) => batch.subjectIds.includes(item.id));
  const sessions = state.sessions.filter((item) => item.batchId === batch.id);
  const pending = assessmentStore.state.assessments.filter((item) => item.status === "Published" && (item.assignedBatchIds || []).includes(batch.id)).length;
  const metrics = [[Users, batch.studentIds.length, "Total students"], [UserCheck, batch.studentIds.length, "Active students"], [TrendingUp, `${batch.completion}%`, "Completion"], [BarChart3, `${batch.averageQuiz}%`, "Quiz average"], [FileText, `${batch.averageAssignment}%`, "Assignment average"], [CalendarDays, `${batch.attendance}%`, "Attendance"], [Clock3, pending || batch.pendingAssignments, "Pending work"], [Bell, sessions.length, "Upcoming sessions"]];
  return <div className="batch-overview"><div className="batch-kpi-grid">{metrics.map(([Icon, value, label]) => <article key={label}><Icon /><div><strong>{value}</strong><span>{label}</span></div></article>)}</div><div className="batch-overview-columns"><section className="workspace-panel"><header><div><span>Curriculum</span><h3>Assigned subjects</h3></div></header><div className="mini-subject-list">{subjects.map((subject) => <article key={subject.id}><i style={{ background: subject.color }}><BookOpen /></i><div><strong>{subject.name}</strong><small>{subject.lessons} lessons • {subject.assignments} assignments • {subject.quizzes} quizzes</small></div></article>)}</div></section><JoinCodeCard batch={batch} store={store} showToast={showToast} /></div></div>;
}

function StudentsTab({ batch }) {
  const students = BATCH_STUDENTS.filter((student) => batch.studentIds.includes(student.id));
  return <section className="workspace-panel batch-student-table"><header><div><span>Enrollment</span><h3>{students.length} students</h3></div><label><Search /><input placeholder="Search students" /></label></header><div className="table-head"><span>Student</span><span>Department</span><span>Progress</span><span>Attendance</span><span>Status</span></div>{students.map((student, index) => <article key={student.id}><span className="batch-student"><b>{student.name.split(" ").map((word) => word[0]).join("")}</b><span><strong>{student.name}</strong><small>{student.email}</small></span></span><span>{student.department}</span><span><strong>{72 + index * 8}%</strong><i><b style={{ width: `${72 + index * 8}%` }} /></i></span><span>{index ? "88%" : "96%"}</span><span className="batch-status active">Active</span></article>)}</section>;
}

function BatchSubjectsTab({ batch, state }) {
  const [selectedId, setSelectedId] = useState("");
  const subjects = state.subjects.filter((item) => batch.subjectIds.includes(item.id));
  const selected = subjects.find((item) => item.id === selectedId);
  if (selected) return <section className="subject-structure"><button className="workspace-back" onClick={() => setSelectedId("")}><ChevronLeft /> Back to subjects</button><header style={{ "--subject-color": selected.color }}><span><BookOpen /></span><div><h2>{selected.name}</h2><p>{selected.description}</p></div></header><div>{[[BookOpen, selected.lessons, "Lessons"], [FileText, selected.assignments, "Assignments"], [BarChart3, selected.quizzes, "Quizzes"], [Clipboard, selected.files, "Study files"], [Clock3, selected.liveSessions, "Live sessions"], [Megaphone, state.announcements.filter((item) => item.batchId === batch.id).length, "Announcements"]].map(([Icon, value, label]) => <article key={label}><Icon /><strong>{value}</strong><span>{label}</span></article>)}</div><p>Use the existing Courses, Content, and Assessments modules to edit the underlying learning items. This subject view keeps them organized for the selected batch.</p></section>;
  return <div className="subject-card-grid">{subjects.map((subject) => <article style={{ "--subject-color": subject.color }} key={subject.id}><header><span><BookOpen /></span><div><h3>{subject.name}</h3><small>{subject.description}</small></div></header><div><span><strong>{subject.lessons}</strong>Lessons</span><span><strong>{subject.assignments}</strong>Assignments</span><span><strong>{subject.quizzes}</strong>Quizzes</span><span><strong>{subject.files}</strong>Files</span></div><footer><span><Clock3 />{subject.liveSessions} live sessions</span><button onClick={() => setSelectedId(subject.id)}>View structure <ChevronRight /></button></footer></article>)}</div>;
}

function AnnouncementsTab({ batch, state, store, user, showToast }) {
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ title: "", message: "" });
  const announcements = state.announcements.filter((item) => item.batchId === batch.id);
  function edit(item = null) { setEditing(item || { id: "" }); setForm(item ? { title: item.title, message: item.message } : { title: "", message: "" }); }
  function save(event) { event.preventDefault(); store.saveAnnouncement({ ...editing, ...form, batchId: batch.id, author: user.name }); setEditing(null); showToast?.(editing.id ? "Announcement updated" : "Announcement published"); }
  return <><div className="tab-heading"><div><h3>Batch announcements</h3><p>Only students enrolled in this batch receive these updates.</p></div><button className="primary" onClick={() => edit()}><Plus /> New announcement</button></div><div className="announcement-list">{announcements.map((item) => <article key={item.id}><span><Megaphone /></span><div><header><div><h3>{item.title}</h3><small>{item.author} • {date(item.createdAt)}</small></div><div><button onClick={() => edit(item)}><Edit3 /></button><button className="danger" onClick={() => { store.deleteAnnouncement(item.id); showToast?.("Announcement deleted"); }}><Trash2 /></button></div></header><p>{item.message}</p></div></article>)}{!announcements.length && <div className="workspace-empty"><Megaphone /><h3>No announcements yet</h3><p>Publish an update for this batch.</p></div>}</div>{editing && <WorkspaceModal title={editing.id ? "Edit announcement" : "Create announcement"} onClose={() => setEditing(null)}><form className="workspace-form" onSubmit={save}><label><span>Title</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label><span>Message</span><textarea rows="6" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} required /></label><footer><button type="button" className="secondary" onClick={() => setEditing(null)}>Cancel</button><button className="primary"><Send /> Publish</button></footer></form></WorkspaceModal>}</>;
}

function AttendanceTab({ batch, state, store, showToast }) {
  const today = "2026-07-06";
  const [subjectId, setSubjectId] = useState(batch.subjectIds[0] || "");
  const existing = state.attendance.find((item) => item.batchId === batch.id && item.date === today && item.subjectId === subjectId);
  const [statuses, setStatuses] = useState(existing?.statuses || Object.fromEntries(batch.studentIds.map((id) => [id, "Present"])));
  const students = BATCH_STUDENTS.filter((item) => batch.studentIds.includes(item.id));
  return <div className="attendance-workspace"><header><div><h3>Mark attendance</h3><p>{date(today)} • Changes can be edited anytime.</p></div><label>Subject<select value={subjectId} onChange={(e) => { setSubjectId(e.target.value); const record = state.attendance.find((item) => item.batchId === batch.id && item.date === today && item.subjectId === e.target.value); setStatuses(record?.statuses || Object.fromEntries(batch.studentIds.map((id) => [id, "Present"]))); }}>{state.subjects.filter((item) => batch.subjectIds.includes(item.id)).map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label></header><section className="attendance-list">{students.map((student) => <article key={student.id}><span className="batch-student"><b>{student.name.split(" ").map((word) => word[0]).join("")}</b><span><strong>{student.name}</strong><small>{student.email}</small></span></span><div>{["Present", "Late", "Absent"].map((status) => <button className={`${status.toLowerCase()} ${statuses[student.id] === status ? "active" : ""}`} key={status} onClick={() => setStatuses({ ...statuses, [student.id]: status })}>{status === "Present" ? <UserCheck /> : status === "Absent" ? <UserMinus /> : <Clock3 />}{status}</button>)}</div></article>)}</section><button className="primary attendance-save" onClick={() => { store.saveAttendance(batch.id, subjectId, today, statuses); showToast?.("Attendance saved"); }}><Check /> Save attendance</button></div>;
}

function DiscussionsTab({ batch, state, store, user, showToast }) {
  const [compose, setCompose] = useState(false);
  const [draft, setDraft] = useState({ subjectId: batch.subjectIds[0] || "", title: "", body: "" });
  const [replies, setReplies] = useState({});
  const discussions = state.discussions.filter((item) => item.batchId === batch.id).sort((a, b) => Number(b.pinned) - Number(a.pinned));
  return <><div className="tab-heading"><div><h3>Discussion forum</h3><p>Ask doubts, share ideas, and pin important threads.</p></div><button className="primary" onClick={() => setCompose(true)}><Plus /> New discussion</button></div><div className="discussion-list">{discussions.map((item) => <article key={item.id} className={item.pinned ? "pinned" : ""}><header><span>{item.author.split(" ").map((word) => word[0]).join("")}</span><div><div><strong>{item.author}</strong><small>{item.role} • {date(item.createdAt)}</small></div><h3>{item.title}</h3></div><button title="Pin discussion" className={item.pinned ? "active" : ""} onClick={() => store.togglePin(item.id)}><Pin /></button></header><p>{item.body}</p><div className="discussion-replies">{item.replies.map((reply) => <blockquote key={reply.id}><strong>{reply.author} <small>{reply.role}</small></strong><p>{reply.text}</p></blockquote>)}</div><footer><input value={replies[item.id] || ""} onChange={(e) => setReplies({ ...replies, [item.id]: e.target.value })} placeholder="Write a reply..." /><button disabled={!replies[item.id]?.trim()} onClick={() => { store.replyDiscussion(item.id, { author: user.name, role: "Teacher", text: replies[item.id] }); setReplies({ ...replies, [item.id]: "" }); showToast?.("Reply posted"); }}><Send /> Reply</button></footer></article>)}</div>{compose && <WorkspaceModal title="Start a discussion" onClose={() => setCompose(false)}><form className="workspace-form" onSubmit={(e) => { e.preventDefault(); store.createDiscussion({ ...draft, batchId: batch.id, authorId: user.id, author: user.name, role: "Teacher" }); setCompose(false); showToast?.("Discussion created"); }}><label><span>Subject</span><select value={draft.subjectId} onChange={(e) => setDraft({ ...draft, subjectId: e.target.value })}>{state.subjects.filter((item) => batch.subjectIds.includes(item.id)).map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select></label><label><span>Title</span><input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} required /></label><label><span>Question or topic</span><textarea rows="5" value={draft.body} onChange={(e) => setDraft({ ...draft, body: e.target.value })} required /></label><footer><button type="button" className="secondary" onClick={() => setCompose(false)}>Cancel</button><button className="primary"><Send /> Post</button></footer></form></WorkspaceModal>}</>;
}

function BatchDetail({ batch, state, store, assessmentStore, onBack, onEdit, user, showToast }) {
  const [tab, setTab] = useState("overview");
  const tabs = [["overview", BarChart3, "Overview"], ["students", Users, "Students"], ["subjects", BookOpen, "Subjects"], ["announcements", Megaphone, "Announcements"], ["attendance", UserCheck, "Attendance"], ["discussions", MessageCircle, "Discussions"]];
  return <section className="teacher-page batch-detail-page"><button className="workspace-back" onClick={onBack}><ChevronLeft /> Back to batches</button><header className="batch-detail-hero"><div><span><Layers3 /></span><div><small>{batch.department} • {batch.semester}, {batch.year}</small><h1>{batch.name}</h1><p>{batch.description}</p></div></div><button onClick={() => onEdit(batch)}><Edit3 /> Edit batch</button></header><nav className="batch-detail-tabs">{tabs.map(([id, Icon, label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}><Icon />{label}</button>)}</nav>{tab === "overview" && <OverviewTab batch={batch} state={state} assessmentStore={assessmentStore} store={store} showToast={showToast} />}{tab === "students" && <StudentsTab batch={batch} />}{tab === "subjects" && <BatchSubjectsTab batch={batch} state={state} />}{tab === "announcements" && <AnnouncementsTab batch={batch} state={state} store={store} user={user} showToast={showToast} />}{tab === "attendance" && <AttendanceTab batch={batch} state={state} store={store} showToast={showToast} />}{tab === "discussions" && <DiscussionsTab batch={batch} state={state} store={store} user={user} showToast={showToast} />}</section>;
}

function BatchesPage({ batchStore, assessmentStore, user, showToast }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("Active"); const [selectedId, setSelectedId] = useState(""); const [editor, setEditor] = useState(null);
  const batch = batchStore.state.batches.find((item) => item.id === selectedId);
  const visible = batchStore.state.batches.filter((item) => (status === "All" || item.status === status) && `${item.name} ${item.subject} ${item.department}`.toLowerCase().includes(query.toLowerCase()));
  if (batch) return <><BatchDetail batch={batch} state={batchStore.state} store={batchStore} assessmentStore={assessmentStore} onBack={() => setSelectedId("")} onEdit={setEditor} user={user} showToast={showToast} />{editor && <BatchEditor initial={editor} user={user} onSave={batchStore.saveBatch} onClose={() => setEditor(null)} showToast={showToast} />}</>;
  return <section className="teacher-page"><div className="teacher-page-heading"><div><span>Class management</span><h1>Batches</h1><p>Create cohorts, manage enrollment, and monitor learning outcomes.</p></div><button className="primary" onClick={() => setEditor(blankBatch(user.name))}><Plus /> Create batch</button></div><div className="workspace-toolbar"><label><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search batches" /></label><div>{["Active", "Archived", "All"].map((item) => <button className={status === item ? "active" : ""} onClick={() => setStatus(item)} key={item}>{item}</button>)}</div></div><BatchCards batches={visible} state={batchStore.state} onOpen={setSelectedId} onEdit={setEditor} onArchive={(id) => { batchStore.archiveBatch(id); showToast?.("Batch status updated"); }} onDelete={(item) => { if (window.confirm(`Delete “${item.name}” and its batch activity?`)) { batchStore.deleteBatch(item.id); showToast?.("Batch deleted"); } }} />{!visible.length && <div className="workspace-empty"><Layers3 /><h3>No matching batches</h3><p>Adjust the search or status filter.</p></div>}{editor && <BatchEditor initial={editor} user={user} onSave={batchStore.saveBatch} onClose={() => setEditor(null)} showToast={showToast} />}</section>;
}

function SubjectsPage({ batchStore, showToast }) {
  const [editor, setEditor] = useState(null); const [query, setQuery] = useState("");
  const subjects = batchStore.state.subjects.filter((item) => item.name.toLowerCase().includes(query.toLowerCase()));
  return <section className="teacher-page"><div className="teacher-page-heading"><div><span>Curriculum library</span><h1>Subjects</h1><p>Create subject workspaces and assign them across batches.</p></div><button className="primary" onClick={() => setEditor(blankSubject())}><Plus /> Create subject</button></div><div className="workspace-toolbar"><label><Search /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search subjects" /></label></div><div className="subject-management-grid">{subjects.map((subject) => <article style={{ "--subject-color": subject.color }} key={subject.id}><header><span><BookOpen /></span><div><h2>{subject.name}</h2><p>{subject.description}</p></div></header><div className="subject-counts"><span><strong>{subject.lessons}</strong>Lessons</span><span><strong>{subject.assignments}</strong>Assignments</span><span><strong>{subject.quizzes}</strong>Quizzes</span><span><strong>{subject.files}</strong>Files</span><span><strong>{subject.liveSessions}</strong>Sessions</span></div><div className="subject-batches"><small>Assigned batches</small><p>{batchStore.state.batches.filter((batch) => subject.assignedBatchIds.includes(batch.id)).map((batch) => batch.name).join(", ") || "Not assigned"}</p></div><footer><button onClick={() => setEditor(subject)}><Edit3 /> Edit</button><button className="danger" onClick={() => { if (window.confirm(`Delete ${subject.name}?`)) batchStore.deleteSubject(subject.id); }}><Trash2 /> Delete</button></footer></article>)}</div>{editor && <SubjectEditor initial={editor} batches={batchStore.state.batches} onSave={batchStore.saveSubject} onClose={() => setEditor(null)} showToast={showToast} />}</section>;
}

function SubjectEditor({ initial, batches, onSave, onClose, showToast }) {
  const [form, setForm] = useState(initial); const update = (field, value) => setForm({ ...form, [field]: value });
  return <WorkspaceModal title={form.id ? "Edit subject" : "Create subject"} subtitle="A subject can be assigned to one or more batches." onClose={onClose} wide><form className="workspace-form" onSubmit={(e) => { e.preventDefault(); onSave({ ...form, lessons: Number(form.lessons), assignments: Number(form.assignments), quizzes: Number(form.quizzes), files: Number(form.files), liveSessions: Number(form.liveSessions) }); showToast?.("Subject saved"); onClose(); }}><div className="workspace-form-grid"><label><span>Subject name</span><input value={form.name} onChange={(e) => update("name", e.target.value)} required /></label><label><span>Accent colour</span><input type="color" value={form.color} onChange={(e) => update("color", e.target.value)} /></label><label className="span-2"><span>Description</span><textarea rows="3" value={form.description} onChange={(e) => update("description", e.target.value)} required /></label>{[["lessons", "Lessons"], ["assignments", "Assignments"], ["quizzes", "Quizzes"], ["files", "Files"], ["liveSessions", "Live sessions"]].map(([field, label]) => <label key={field}><span>{label}</span><input type="number" min="0" value={form[field]} onChange={(e) => update(field, e.target.value)} /></label>)}</div><fieldset className="batch-checkboxes"><legend>Assign to batches</legend>{batches.filter((batch) => batch.status === "Active").map((batch) => <label key={batch.id}><input type="checkbox" checked={form.assignedBatchIds.includes(batch.id)} onChange={(e) => update("assignedBatchIds", e.target.checked ? [...form.assignedBatchIds, batch.id] : form.assignedBatchIds.filter((id) => id !== batch.id))} /><span>{batch.name}<small>{batch.studentIds.length} students</small></span></label>)}</fieldset><footer><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary"><Check /> Save subject</button></footer></form></WorkspaceModal>;
}

function TeacherCalendar({ batchStore, assessmentStore, store }) {
  const events = [
    ...batchStore.state.sessions.map((item) => ({ ...item, type: "Live session", batch: batchStore.state.batches.find((batch) => batch.id === item.batchId)?.name })),
    ...assessmentStore.state.assessments.filter((item) => item.status === "Published").map((item) => ({ id: item.id, title: item.title, startAt: item.dueAt, type: item.type === "quiz" ? "Quiz deadline" : "Assignment deadline", batch: item.className })),
    ...(store?.events || []).filter(e => e.status !== "Draft").map((item) => ({ id: item.id, title: item.title, startAt: item.timeline, type: "Campus Event", batch: "Campus" }))
  ].sort((a, b) => new Date(a.startAt) - new Date(b.startAt));
  return <section className="teacher-page"><div className="teacher-page-heading"><div><span>Learning schedule</span><h1>Calendar</h1><p>Assignments, quizzes, deadlines, and live sessions in one timeline.</p></div></div><div className="calendar-layout"><aside><CalendarDays /><strong>July 2026</strong><div className="calendar-mini-grid">{[...Array(31)].map((_, index) => <span className={[8,9,10,12,13,15].includes(index + 1) ? "has-event" : index + 1 === 6 ? "today" : ""} key={index}>{index + 1}</span>)}</div></aside><section className="calendar-event-list">{events.map((event) => <article key={event.id}><time><strong>{new Date(event.startAt).getDate()}</strong><small>{new Date(event.startAt).toLocaleString("en", { month: "short" })}</small></time><span className={event.type.includes("session") ? "session" : event.type.includes("Event") ? "session" : "deadline"}>{event.type.includes("session") ? <Clock3 /> : event.type.includes("Event") ? <CalendarDays /> : <FileText />}</span><div><strong>{event.title}</strong><small>{event.batch}</small></div><b>{date(event.startAt)}</b></article>)}</section></div></section>;
}

function TeacherAnalytics({ batchStore }) {
  const active = batchStore.state.batches.filter((item) => item.status === "Active");
  const students = BATCH_STUDENTS.map((student, index) => ({ ...student, progress: [82, 91, 48][index], score: [86, 92, 58][index] }));
  return <section className="teacher-page"><div className="teacher-page-heading"><div><span>Performance intelligence</span><h1>Teacher Analytics</h1><p>Student progress, completion, marks, and cohort health.</p></div></div><div className="analytics-kpi-grid"><article><Users /><span><strong>{new Set(active.flatMap((item) => item.studentIds)).size}</strong>Active students</span></article><article><TrendingUp /><span><strong>{Math.round(active.reduce((sum, item) => sum + item.completion, 0) / active.length)}%</strong>Course completion</span></article><article><BarChart3 /><span><strong>{Math.round(active.reduce((sum, item) => sum + item.averageAssignment, 0) / active.length)}%</strong>Average marks</span></article><article><FileText /><span><strong>{active.reduce((sum, item) => sum + item.pendingAssignments, 0)}</strong>Pending assignments</span></article></div><div className="analytics-main-grid"><section className="workspace-panel"><header><div><span>Cohort comparison</span><h3>Batch performance</h3></div></header><div className="batch-performance-bars">{active.map((batch) => <article key={batch.id}><div><strong>{batch.name}</strong><small>{batch.studentIds.length} students</small></div><span><i style={{ width: `${batch.completion}%` }} /></span><b>{batch.completion}%</b></article>)}</div></section><section className="workspace-panel"><header><div><span>Needs attention</span><h3>Weak students</h3></div></header><div className="analytics-student-list">{students.filter((item) => item.progress < 60).map((student) => <article key={student.id}><span>{student.name.split(" ").map((word) => word[0]).join("")}</span><div><strong>{student.name}</strong><small>{student.progress}% progress • {student.score}% average</small></div><button>View</button></article>)}</div></section><section className="workspace-panel top-performers"><header><div><span>High achievement</span><h3>Top performers</h3></div></header>{students.sort((a, b) => b.score - a.score).slice(0, 3).map((student, index) => <article key={student.id}><b>{index + 1}</b><span><strong>{student.name}</strong><small>{student.progress}% completion</small></span><em>{student.score}%</em></article>)}</section></div></section>;
}

export default function TeacherBatchWorkspace({ mode, batchStore, assessmentStore, user, showToast, store }) {
  if (mode === "subjects") return <SubjectsPage batchStore={batchStore} showToast={showToast} />;
  if (mode === "calendar") return <TeacherCalendar batchStore={batchStore} assessmentStore={assessmentStore} store={store} />;
  if (mode === "analytics") return <TeacherAnalytics batchStore={batchStore} />;
  return <BatchesPage batchStore={batchStore} assessmentStore={assessmentStore} user={user} showToast={showToast} />;
}
