import { useMemo, useState } from "react";
import {
  ArrowLeft, BarChart3, Bell, BookOpen, CalendarDays, CheckCircle2, ChevronRight,
  ClipboardCheck, Clock3, FileText, GraduationCap, Hash, Layers3, Link2, Megaphone,
  MessageCircle, Pin, Plus, Search, Send, TrendingUp, Trophy, UserCheck, Users
} from "lucide-react";
import { BATCH_STUDENTS } from "../batches/batch.data.js";

function date(value) { return new Intl.DateTimeFormat("en-IN", { day: "numeric", month: "short", year: "numeric", hour: value?.includes("T") ? "numeric" : undefined, minute: value?.includes("T") ? "2-digit" : undefined }).format(new Date(value)); }

function JoinBatchCard({ batchStore, user, showToast }) {
  const [code, setCode] = useState(""); const [error, setError] = useState("");
  function join(event) { event.preventDefault(); const result = batchStore.joinBatch(code, user.studentId || user.id); if (result.ok) { setCode(""); setError(""); showToast?.(`Joined ${result.batch.name}`); } else setError(result.error); }
  return <section className="student-join-card"><span><Hash /></span><div><h2>Join a batch</h2><p>Enter the code shared by your teacher to join instantly.</p><form onSubmit={join}><input value={code} onChange={(e) => { setCode(e.target.value.toUpperCase()); setError(""); }} placeholder="ABC-123" maxLength="7" /><button className="primary" disabled={!code.trim()}>Join batch</button></form>{error && <small>{error}</small>}</div></section>;
}

function StudentBatchList({ batchStore, assessmentStore, user, onOpen, showToast }) {
  const studentId = user.studentId || user.id;
  const batches = batchStore.state.batches.filter((batch) => batch.studentIds.includes(studentId) && batch.status === "Active");
  return <section><div className="student-page-title"><div><span>Learning communities</span><h1>My Batches</h1><p>Subjects, announcements, attendance, sessions, and class discussions.</p></div></div><JoinBatchCard batchStore={batchStore} user={user} showToast={showToast} /><div className="student-batch-grid">{batches.map((batch) => { const pending = assessmentStore.state.assessments.filter((item) => item.status === "Published" && (item.assignedBatchIds || []).includes(batch.id) && !assessmentStore.state.submissions.some((submission) => submission.assessmentId === item.id && submission.studentId === studentId)).length; return <article key={batch.id}><header><span><Layers3 /></span><div><small>{batch.department} • {batch.semester}</small><h2>{batch.name}</h2></div></header><p>{batch.description}</p><div className="student-batch-stats"><span><BookOpen /><strong>{batch.subjectIds.length}</strong>Subjects</span><span><ClipboardCheck /><strong>{pending}</strong>Pending</span><span><UserCheck /><strong>{batch.attendance}%</strong>Attendance</span></div><div className="student-batch-progress"><span><strong>{batch.completion}%</strong> course completion</span><div><i style={{ width: `${batch.completion}%` }} /></div></div><footer><span><GraduationCap />{batch.teacher}</span><button onClick={() => onOpen(batch.id)}>Open batch <ChevronRight /></button></footer></article>; })}{!batches.length && <div className="student-empty"><Layers3 /><h2>No batches yet</h2><p>Use a teacher-provided join code to get started.</p></div>}</div></section>;
}

function StudentDiscussions({ batch, state, store, user, showToast }) {
  const [compose, setCompose] = useState(false); const [draft, setDraft] = useState({ subjectId: batch.subjectIds[0] || "", title: "", body: "" }); const [replies, setReplies] = useState({});
  const discussions = state.discussions.filter((item) => item.batchId === batch.id).sort((a, b) => Number(b.pinned) - Number(a.pinned));
  return <section><div className="student-batch-tab-heading"><div><h2>Discussion forum</h2><p>Ask doubts and learn with your batch.</p></div><button className="primary" onClick={() => setCompose(!compose)}><Plus /> New post</button></div>{compose && <form className="student-discussion-compose" onSubmit={(e) => { e.preventDefault(); store.createDiscussion({ ...draft, batchId: batch.id, authorId: user.studentId || user.id, author: user.name, role: "Student" }); setCompose(false); setDraft({ subjectId: batch.subjectIds[0] || "", title: "", body: "" }); showToast?.("Discussion posted"); }}><select value={draft.subjectId} onChange={(e) => setDraft({ ...draft, subjectId: e.target.value })}>{state.subjects.filter((item) => batch.subjectIds.includes(item.id)).map((subject) => <option value={subject.id} key={subject.id}>{subject.name}</option>)}</select><input value={draft.title} onChange={(e) => setDraft({ ...draft, title: e.target.value })} placeholder="Discussion title" required /><textarea rows="4" value={draft.body} onChange={(e) => setDraft({ ...draft, body: e.target.value })} placeholder="Ask your question or share an idea..." required /><button className="primary"><Send /> Post discussion</button></form>}<div className="student-discussion-list">{discussions.map((item) => <article className={item.pinned ? "pinned" : ""} key={item.id}><header><span>{item.author.split(" ").map((word) => word[0]).join("")}</span><div><strong>{item.author}</strong><small>{item.role} • {date(item.createdAt)}</small></div><button className={item.pinned ? "active" : ""} title={item.pinned ? "Unpin discussion" : "Pin discussion"} onClick={() => { store.togglePin(item.id); showToast?.(item.pinned ? "Discussion unpinned" : "Discussion pinned"); }}><Pin />{item.pinned ? "Pinned" : "Pin"}</button></header><h3>{item.title}</h3><p>{item.body}</p>{item.replies.map((reply) => <blockquote key={reply.id}><strong>{reply.author} <small>{reply.role}</small></strong><p>{reply.text}</p></blockquote>)}<footer><input value={replies[item.id] || ""} onChange={(e) => setReplies({ ...replies, [item.id]: e.target.value })} placeholder="Reply to this discussion..." /><button disabled={!replies[item.id]?.trim()} onClick={() => { store.replyDiscussion(item.id, { author: user.name, role: "Student", text: replies[item.id] }); setReplies({ ...replies, [item.id]: "" }); showToast?.("Reply posted"); }}><Send /> Reply</button></footer></article>)}</div></section>;
}

function StudentBatchDetail({ batch, batchStore, assessmentStore, user, onBack, showToast }) {
  const [tab, setTab] = useState("overview"); const studentId = user.studentId || user.id;
  const subjects = batchStore.state.subjects.filter((item) => batch.subjectIds.includes(item.id));
  const announcements = batchStore.state.announcements.filter((item) => item.batchId === batch.id);
  const sessions = batchStore.state.sessions.filter((item) => item.batchId === batch.id);
  const attendance = batchStore.state.attendance.filter((item) => item.batchId === batch.id && item.statuses[studentId]);
  const present = attendance.filter((item) => item.statuses[studentId] === "Present").length;
  const assigned = assessmentStore.state.assessments.filter((item) => item.status === "Published" && ((item.assignedBatchIds || []).includes(batch.id) || (item.assignedStudentIds || []).includes(studentId)));
  const tabs = [["overview", BarChart3, "Overview"], ["subjects", BookOpen, "Subjects"], ["assignments", ClipboardCheck, "Assignments"], ["attendance", UserCheck, "Attendance"], ["sessions", CalendarDays, "Live sessions"], ["materials", FileText, "Materials"], ["announcements", Megaphone, "Announcements"], ["discussions", MessageCircle, "Discussions"]];
  return <section className="student-batch-detail"><button className="student-back" onClick={onBack}><ArrowLeft /> Back to My Batches</button><header className="student-batch-hero"><div><span><Layers3 /></span><div><small>{batch.department} • {batch.semester}, {batch.year}</small><h1>{batch.name}</h1><p>{batch.description}</p></div></div><aside><GraduationCap /><span><small>Teacher</small><strong>{batch.teacher}</strong></span></aside></header><nav className="student-batch-tabs">{tabs.map(([id, Icon, label]) => <button className={tab === id ? "active" : ""} onClick={() => setTab(id)} key={id}><Icon />{label}</button>)}</nav>
    {tab === "overview" && <><div className="student-batch-kpis"><article><TrendingUp /><span><strong>{batch.completion}%</strong>Completion</span></article><article><Trophy /><span><strong>{batch.averageQuiz}%</strong>Quiz average</span></article><article><FileText /><span><strong>{batch.averageAssignment}%</strong>Assignment average</span></article><article><UserCheck /><span><strong>{attendance.length ? Math.round((present / attendance.length) * 100) : batch.attendance}%</strong>Attendance</span></article></div><div className="student-batch-overview-grid"><section className="student-batch-panel"><header><div><span>Latest updates</span><h2>Announcements</h2></div></header>{announcements.slice(0, 3).map((item) => <article className="student-announcement-mini" key={item.id}><Megaphone /><div><strong>{item.title}</strong><p>{item.message}</p><small>{date(item.createdAt)}</small></div></article>)}</section><section className="student-batch-panel"><header><div><span>Schedule</span><h2>Upcoming sessions</h2></div></header>{sessions.map((session) => <article className="student-session-mini" key={session.id}><time><strong>{new Date(session.startAt).getDate()}</strong><small>{new Date(session.startAt).toLocaleString("en", { month: "short" })}</small></time><div><strong>{session.title}</strong><small>{date(session.startAt)} • {session.duration}</small></div></article>)}</section></div></>}
    {tab === "subjects" && <div className="student-subject-grid">{subjects.map((subject) => <article style={{ "--subject-color": subject.color }} key={subject.id}><header><span><BookOpen /></span><div><h2>{subject.name}</h2><p>{subject.description}</p></div></header><div><span><strong>{subject.lessons}</strong>Lessons</span><span><strong>{subject.assignments}</strong>Assignments</span><span><strong>{subject.quizzes}</strong>Quizzes</span></div><button onClick={() => setTab("materials")}>Open materials <ChevronRight /></button></article>)}</div>}
    {tab === "assignments" && <div className="student-batch-assignment-list">{assigned.map((item) => { const submission = assessmentStore.state.submissions.find((entry) => entry.assessmentId === item.id && entry.studentId === studentId); return <article key={item.id}><span className={item.type}><FileText /></span><div><small>{item.subject}</small><h3>{item.title}</h3><p>Due {date(item.dueAt)}</p></div><b className={submission ? submission.status.toLowerCase() : "todo"}>{submission ? submission.status : "To do"}</b></article>; })}</div>}
    {tab === "attendance" && <section className="student-attendance-view"><header><div><strong>{attendance.length ? Math.round((present / attendance.length) * 100) : batch.attendance}%</strong><span>Overall attendance</span></div><p>{present} present • {attendance.length - present} late or absent • {attendance.length} sessions recorded</p></header>{attendance.map((item) => <article key={item.id}><time>{date(item.date)}</time><span>{subjects.find((subject) => subject.id === item.subjectId)?.name}</span><b className={item.statuses[studentId].toLowerCase()}>{item.statuses[studentId]}</b></article>)}</section>}
    {tab === "sessions" && <div className="student-live-session-list">{sessions.map((session) => <article key={session.id}><time><strong>{new Date(session.startAt).getDate()}</strong><small>{new Date(session.startAt).toLocaleString("en", { month: "short" })}</small></time><div><small>{subjects.find((subject) => subject.id === session.subjectId)?.name}</small><h3>{session.title}</h3><p>{date(session.startAt)} • {session.duration}</p></div><button><Link2 /> Session details</button></article>)}</div>}
    {tab === "materials" && <div className="student-material-grid">{subjects.map((subject) => <article key={subject.id}><span style={{ color: subject.color }}><FileText /></span><div><h3>{subject.name} study pack</h3><p>{subject.files} files • Notes, references, and lab resources</p></div><button>View materials <ChevronRight /></button></article>)}</div>}
    {tab === "announcements" && <div className="student-announcement-list">{announcements.map((item) => <article key={item.id}><span><Megaphone /></span><div><h3>{item.title}</h3><small>{item.author} • {date(item.createdAt)}</small><p>{item.message}</p></div></article>)}</div>}
    {tab === "discussions" && <StudentDiscussions batch={batch} state={batchStore.state} store={batchStore} user={user} showToast={showToast} />}
  </section>;
}

function StudentCalendar({ batchStore, assessmentStore, user, store }) {
  const studentId = user.studentId || user.id;
  const batchIds = batchStore.state.batches.filter((item) => item.studentIds.includes(studentId)).map((item) => item.id);
  const events = [
    ...batchStore.state.sessions.filter((item) => batchIds.includes(item.batchId)).map((item) => ({ ...item, type: "Live session" })),
    ...assessmentStore.state.assessments.filter((item) => item.status === "Published" && ((item.assignedBatchIds || []).some((id) => batchIds.includes(id)) || (item.assignedStudentIds || []).includes(studentId))).map((item) => ({ id: item.id, title: item.title, startAt: item.dueAt, type: item.type === "quiz" ? "Quiz deadline" : "Assignment deadline" })),
    ...(store?.events || []).filter(e => e.status !== "Draft" && (store?.registrations || []).some(r => r.eventId === e.id && r.studentId === studentId)).map((item) => ({ id: item.id, title: item.title, startAt: item.timeline, type: "Campus Event" }))
  ].sort((a, b) => new Date(a.startAt) - new Date(b.startAt));
  return <section><div className="student-page-title"><div><span>My schedule</span><h1>Calendar</h1><p>Assignments, quizzes, deadlines, and live sessions.</p></div></div><div className="student-calendar-layout"><aside><CalendarDays /><strong>July 2026</strong><div>{[...Array(31)].map((_, index) => <span className={[8,9,10,12,13,15].includes(index + 1) ? "event" : index + 1 === 6 ? "today" : ""} key={index}>{index + 1}</span>)}</div></aside><section>{events.map((event) => <article key={event.id}><time><strong>{new Date(event.startAt).getDate()}</strong><small>{new Date(event.startAt).toLocaleString("en", { month: "short" })}</small></time><span className={event.type.includes("session") ? "session" : event.type.includes("Event") ? "session" : "deadline"}>{event.type.includes("session") ? <Clock3 /> : event.type.includes("Event") ? <CalendarDays /> : <FileText />}</span><div><strong>{event.title}</strong><small>{event.type} • {date(event.startAt)}</small></div></article>)}</section></div></section>;
}

function StudentAnalytics({ batchStore, assessmentStore, user, studentState }) {
  const studentId = user.studentId || user.id; const batches = batchStore.state.batches.filter((item) => item.studentIds.includes(studentId)); const submissions = assessmentStore.state.submissions.filter((item) => item.studentId === studentId); const graded = submissions.filter((item) => item.status === "Graded");
  const average = studentState?.assessmentAverage || 0;
  const weeklyHours = studentState?.weeklyLearning?.totalHours || "0h";
  const chartData = studentState?.weeklyLearning?.chartData || [];
  
  return <section><div className="student-page-title"><div><span>Learning insights</span><h1>My Analytics</h1><p>Progress, weekly learning, quiz performance, and assignment status.</p></div></div><div className="student-analytics-kpis"><article><TrendingUp /><span><strong>{batches.length ? Math.round(batches.reduce((sum, item) => sum + item.completion, 0) / batches.length) : 0}%</strong>Overall progress</span></article><article><Clock3 /><span><strong>{weeklyHours}</strong>Weekly learning</span></article><article><Trophy /><span><strong>{average}%</strong>Assessment average</span></article><article><ClipboardCheck /><span><strong>{submissions.length}</strong>Submitted work</span></article></div><div className="student-analytics-grid"><section className="student-batch-panel"><header><div><span>Last 7 days</span><h2>Weekly learning</h2></div></header><div className="weekly-bars">{chartData.map(([day,value]) => <span key={day}><i style={{ height: `${value}%` }} /><small>{day}</small></span>)}</div></section><section className="student-batch-panel"><header><div><span>Batch progress</span><h2>Course completion</h2></div></header>{batches.map((batch) => <article className="student-progress-row" key={batch.id}><div><strong>{batch.name}</strong><small>{batch.subjectIds.length} subjects</small></div><span><i style={{ width: `${batch.completion}%` }} /></span><b>{batch.completion}%</b></article>)}</section><section className="student-batch-panel"><header><div><span>Assessment health</span><h2>Assignment status</h2></div></header><div className="student-status-donut"><span><strong>{graded.length}</strong>Graded</span><span><strong>{submissions.filter((item) => item.status === "Submitted").length}</strong>Review</span><span><strong>{assessmentStore.state.assessments.length - submissions.length}</strong>To do</span></div></section></div></section>;
}

export default function StudentBatchWorkspace({ mode, batchStore, assessmentStore, user, showToast, store, studentState }) {
  const [selectedId, setSelectedId] = useState("");
  const selected = batchStore.state.batches.find((item) => item.id === selectedId);
  if (mode === "calendar") return <StudentCalendar batchStore={batchStore} assessmentStore={assessmentStore} user={user} store={store} />;
  if (mode === "analytics") return <StudentAnalytics batchStore={batchStore} assessmentStore={assessmentStore} user={user} studentState={studentState} />;
  if (selected) return <StudentBatchDetail batch={selected} batchStore={batchStore} assessmentStore={assessmentStore} user={user} onBack={() => setSelectedId("")} showToast={showToast} />;
  return <StudentBatchList batchStore={batchStore} assessmentStore={assessmentStore} user={user} onOpen={setSelectedId} showToast={showToast} />;
}
