server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: lms-course-module

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/lms_course}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:ANAGHA2005}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha